---
title: "Targeted Hormone Analysis"
author: "Sneha Chaturvedi"
date: "July 16, 2025"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) {
  install.packages("pacman")
  library(pacman)
} 
p_load(tidyverse,readxl,dplyr,stats,ggplot2,ggpubr,svglite,knitr)

svg_path <- "../../results/targeted/"
```

# Set Up
```{r LoadDataset, echo=TRUE}
#Load Dataset
targeted = read_excel('../../doc/targeted/targeted_hormones.xlsx',sheet="DATA",range=NULL)
#Create separate datasets by sex
female_targeted <- filter(targeted, Sex == 'F')
male_targeted <- filter(targeted, Sex == 'M')

#convert sex column to factor
targeted$Sex <- as.factor(targeted$Sex)
targeted$`TT (ng/mL)`<- as.numeric(targeted$`TT (ng/mL)`)
targeted$`P4 (ng/mL)`<- as.numeric(targeted$`P4 (ng/mL)`)
targeted$`17B-E2 (ng/mL)`<- as.numeric(targeted$`17B-E2 (ng/mL)`)

#Load Functions
detect_outliers <- function(data, variables) {
  for (variable in variables) {
  #Calculate the outlier limit
  outlier_limit <- quantile(data[[variable]], 0.75, na.rm = TRUE) + 1.5 * IQR(data[[variable]], na.rm = TRUE)
  #Find outliers
  outliers <- data %>% filter(.data[[variable]] > outlier_limit)
  #Print out outliers
  print(paste("Outliers for:", variable))
  print(outliers)
  #Create dataframe with outliers removed
  filtered_data <- data %>% filter(.data[[variable]] <= outlier_limit)
  }
  return(filtered_data)
}
```
# QC
## Raw Data Distribution
```{r visualize_raw, echo=TRUE}
#convert sex column to factor and ensure hormone values are numeric
targeted$Sex <- as.factor(targeted$Sex)
targeted$`TT (ng/mL)`<- as.numeric(targeted$`TT (ng/mL)`)
targeted$`P4 (ng/mL)`<- as.numeric(targeted$`P4 (ng/mL)`)
targeted$`17B-E2 (ng/mL)`<- as.numeric(targeted$`17B-E2 (ng/mL)`)

# Plot the distribution of TT (ng/mL) for the entire dataset
ggplot(targeted, aes(x = `TT (ng/mL)`)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30, fill = 'blue') +
  ggtitle('Distribution of TT (ng/mL) - Total') +
  xlab('TT (ng/mL)') +
  ylab('Count')
ggsave("tt_distribution.svg", path = svg_path)

# QQ plot for total distribution
ggqqplot(targeted$`TT (ng/mL)`) +
  labs(title = "QQ Plot of TT (ng/mL) - Total")
ggsave("tt_QQ.svg", path = svg_path)

# Plot the distribution of TT (ng/mL) by Sex
ggplot(targeted, aes(x = `TT (ng/mL)`, fill = Sex)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30) +
  facet_wrap(~ Sex) +
  ggtitle('Distribution of TT (ng/mL) by Sex') +
  xlab('TT (ng/mL)') +
  ylab('Count')
ggsave("tt_distribution_sex.svg", path = svg_path)


# Plot the distribution of 17B-E2 (ng/mL) for the entire dataset
ggplot(targeted, aes(x = `17B-E2 (ng/mL)`)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30, fill = 'blue') +
  ggtitle('Distribution of 17B-E2 (ng/mL) - Total') +
  xlab('17B-E2 (ng/mL)') +
  ylab('Count')
ggsave("e2_distribution.svg", path = svg_path)

# Generate QQ plots
# QQ plot for total distribution
ggqqplot(targeted$`17B-E2 (ng/mL)`) +
  labs(title = "QQ Plot of 17B-E2 (ng/mL) - Total")
ggsave("e2_QQ.svg", path = svg_path)

# Check the distribution of 17B-E2 (ng/mL) by Sex
ggplot(targeted, aes(x = `17B-E2 (ng/mL)`, fill = Sex)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30) +
  facet_wrap(~ Sex) +
  ggtitle('Distribution of 17B-E2 (ng/mL) by Sex') +
  xlab('17B-E2 (ng/mL)') +
  ylab('Count')
ggsave("e2_distribution_sex.svg", path = svg_path)


# Plot the distribution of P4 (ng/mL) for the entire dataset
ggplot(targeted, aes(x = `P4 (ng/mL)`)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30, fill = 'blue') +
  ggtitle('Distribution of P4 (ng/mL) - Total') +
  xlab('P4 (ng/mL)') +
  ylab('Count')
ggsave("p4_distribution.svg", path = svg_path)

# Generate QQ plots
# QQ plot for total distribution
ggqqplot(targeted$`P4 (ng/mL)`) +
  labs(title = "QQ Plot of P4 (ng/mL) - Total")
ggsave("p4_QQ.svg", path = svg_path)

# Check the distribution of P4 (ng/mL) by Sex
ggplot(targeted, aes(x = `P4 (ng/mL)`, fill = Sex)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30) +
  facet_wrap(~ Sex) +
  ggtitle('Distribution of P4 (ng/mL) by Sex') +
  xlab('P4 (ng/mL)') +
  ylab('Count')
ggsave("p4_distribution_sex.svg", path = svg_path)
```

## Tests of Normality
```{r Normality, echo=TRUE}
# Perform Shapiro-Wilk normality test for each sex group
  all_shapiro_tt <- shapiro.test(targeted$`TT (ng/mL)`)
  m_shapiro_tt <- shapiro.test(male_targeted$`TT (ng/mL)`)
  f_shapiro_tt <- shapiro.test(female_targeted$`TT (ng/mL)`)
  
all_shapiro_e2 <- shapiro.test(targeted$`17B-E2 (ng/mL)`)
  m_shapiro_e2 <- shapiro.test(male_targeted$`17B-E2 (ng/mL)`)
  f_shapiro_e2 <- shapiro.test(female_targeted$`17B-E2 (ng/mL)`)

all_shapiro_p4 <- shapiro.test(targeted$`P4 (ng/mL)`)
  m_shapiro_p4 <- shapiro.test(male_targeted$`P4 (ng/mL)`)
  f_shapiro_p4 <- shapiro.test(female_targeted$`P4 (ng/mL)`)
  

# Create a summary data frame with the results
shapiro_results <- data.frame(
  Group = c('All', 'Male', 'Female'),
  TT_p_value = formatC(c(all_shapiro_tt$p.value, m_shapiro_tt$p.value, f_shapiro_tt$p.value), format = "e", digits = 2),
  E2_p_value = formatC(c(all_shapiro_e2$p.value, m_shapiro_e2$p.value, f_shapiro_e2$p.value), format = "e", digits = 2),
  P4_p_value = formatC(c(all_shapiro_p4$p.value, m_shapiro_p4$p.value, f_shapiro_p4$p.value), format = "e", digits = 2)
)

# Print the results in a table
kable(shapiro_results, caption = "Shapiro-Wilk Normality Test Results (Raw)")

```
# Data Filtering and Clean Up

## Outlier Detection + Removal
```{r outlier, echo=TRUE}
# Create a new dataset with outliers removed
hormones <- c("TT (ng/mL)", "17B-E2 (ng/mL)", "P4 (ng/mL)")
clean_targeted <- detect_outliers(targeted, hormones)
```

```{r re-visualize, echo=TRUE}
# Plot the distribution of TT (ng/mL) for the entire dataset
ggplot(clean_targeted, aes(x = `TT (ng/mL)`)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30, fill = 'blue') +
  ggtitle('Distribution of TT (ng/mL) - Total') +
  xlab('TT (ng/mL)') +
  ylab('Count')
ggsave("clean_tt_distribution.svg", path = svg_path)

# QQ plot for total distribution
ggqqplot(clean_targeted$`TT (ng/mL)`) +
  labs(title = "QQ Plot of TT (ng/mL) - Total")
ggsave("clean_tt_QQ.svg", path = svg_path)

# Check the distribution of TT (ng/mL) by Sex
ggplot(clean_targeted, aes(x = `TT (ng/mL)`, fill = Sex)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30) +
  facet_wrap(~ Sex) +
  ggtitle('Distribution of TT (ng/mL) by Sex') +
  xlab('TT (ng/mL)') +
  ylab('Count')
ggsave("clean_tt_distribution_sex.svg", path = svg_path)


# Plot the distribution of 17B-E2 (ng/mL) for the entire dataset
ggplot(clean_targeted, aes(x = `17B-E2 (ng/mL)`)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30, fill = 'blue') +
  ggtitle('Distribution of 17B-E2 (ng/mL) - Total') +
  xlab('17B-E2 (ng/mL)') +
  ylab('Count')
ggsave("clean_e2_distribution.svg", path = svg_path)

# QQ plot for total distribution
ggqqplot(clean_targeted$`17B-E2 (ng/mL)`) +
  labs(title = "QQ Plot of 17B-E2 (ng/mL) - Total")
ggsave("clean_e2_QQ.svg", path = svg_path)

# Check the distribution of 17B-E2 (ng/mL) Sex
ggplot(clean_targeted, aes(x = `17B-E2 (ng/mL)`, fill = Sex)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30) +
  facet_wrap(~ Sex) +
  ggtitle('Distribution of 17B-E2 (ng/mL) by Sex') +
  xlab('17B-E2 (ng/mL)') +
  ylab('Count')
ggsave("clean_e2_distribution_sex.svg", path = svg_path)

# Plot the distribution of P4 (ng/mL) for the entire dataset
ggplot(clean_targeted, aes(x = `P4 (ng/mL)`)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30, fill = 'blue') +
  ggtitle('Distribution of P4 (ng/mL) - Total') +
  xlab('P4 (ng/mL)') +
  ylab('Count')
ggsave("clean_p4_distribution.svg", path = svg_path)

# QQ plot for total distribution
ggqqplot(clean_targeted$`P4 (ng/mL)`) +
  labs(title = "QQ Plot of P4 (ng/mL) - Total")
ggsave("clean_p4_QQ.svg", path = svg_path)

# Check the distribution of P4 (ng/mL) by Sex
ggplot(clean_targeted, aes(x = `P4 (ng/mL)`, fill = Sex)) +
  geom_histogram(alpha = 0.7, position = 'identity', bins = 30) +
  facet_wrap(~ Sex) +
  ggtitle('Distribution of P4 (ng/mL) by Sex') +
  xlab('P4 (ng/mL)') +
  ylab('Count')
ggsave("clean_p4_distribution_sex.svg", path = svg_path)
```

```{r re-normality, echo = TRUE}
#Create separate datasets by sex
female_clean_targeted <- filter(clean_targeted, Sex == 'F')
male_clean_targeted <- filter(clean_targeted, Sex == 'M')

# Perform Shapiro-Wilk normality test for each sex group
  clean_all_shapiro_tt <- shapiro.test(clean_targeted$`TT (ng/mL)`)
  clean_m_shapiro_tt <- shapiro.test(male_clean_targeted$`TT (ng/mL)`)
  clean_f_shapiro_tt <- shapiro.test(female_clean_targeted$`TT (ng/mL)`)

clean_all_shapiro_e2 <- shapiro.test(clean_targeted$`17B-E2 (ng/mL)`)
clean_m_shapiro_e2 <- shapiro.test(male_clean_targeted$`17B-E2 (ng/mL)`)
clean_f_shapiro_e2 <- shapiro.test(female_clean_targeted$`17B-E2 (ng/mL)`)

clean_all_shapiro_p4 <- shapiro.test(clean_targeted$`P4 (ng/mL)`)
clean_m_shapiro_p4 <- shapiro.test(male_clean_targeted$`P4 (ng/mL)`)
clean_f_shapiro_p4 <- shapiro.test(female_clean_targeted$`P4 (ng/mL)`)
  

# Create a summary data frame with the results
clean_shapiro_results <- data.frame(
  Group = c('All', 'Male', 'Female'),
  TT_p_value = formatC(c(clean_all_shapiro_tt$p.value, clean_m_shapiro_tt$p.value, clean_f_shapiro_tt$p.value), format = "e", digits = 2),
  E2_p_value = formatC(c(clean_all_shapiro_e2$p.value, clean_m_shapiro_e2$p.value, clean_f_shapiro_e2$p.value), format = "e", digits = 2),
  P4_p_value = formatC(c(clean_all_shapiro_p4$p.value, clean_m_shapiro_p4$p.value, clean_f_shapiro_p4$p.value), format = "e", digits = 2)
)

# Print the results in a table
kable(clean_shapiro_results, caption = "Shapiro-Wilk Normality Test Results (Clean)")


```

# Testosterone Analysis
```{r TT_SexComparison}

# Check the p-values
# If  > 0.05, we assume normality and can use a parametric test (t-test)
# Otherwise, use a non-parametric test (Wilcoxon rank-sum test)

if (all_shapiro_tt$p.value > 0.05) {
  # Perform t-test
  tt_t_test <- t.test(`TT (ng/mL)` ~ Sex, data = targeted)
  tt_test_type <- "t-test"
  tt_test_statistic <- tt_t_test$statistic
  tt_p_value <- tt_t_test$p.value
  print(tt_t_test)
} else {
  # Perform Wilcoxon rank-sum test
  tt_wilcox_test <- wilcox.test(`TT (ng/mL)` ~ Sex, data = targeted)
  tt_test_type <- "Wilcoxon rank-sum test"
  tt_test_statistic <- tt_wilcox_test$statistic
  tt_p_value <- tt_wilcox_test$p.value
  print(tt_wilcox_test)
}

# Visualize results with boxplot
ggboxplot(targeted, x = "Sex", y = "`TT (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "TT (ng/mL)", xlab = "Sex",
          add = "jitter") +
  labs(title = paste(tt_test_type, ": statistic =", round(tt_test_statistic, 2), ": pvalue =", formatC(tt_p_value, format = "e", digits = 2)))
ggsave("tt_statistics_sex.svg", path = svg_path)

# Visualize results with boxplot + log y scale
ggboxplot(targeted, x = "Sex", y = "`TT (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "Log 10 TT (ng/mL)", xlab = "Sex",
          add = "jitter") +
  scale_y_log10() +
  labs(title = paste(tt_test_type, ": statistic =", round(tt_test_statistic, 2), ": pvalue =", formatC(tt_p_value, format = "e", digits = 2)))
ggsave("log_tt_statistics_sex.svg", path = svg_path)

# Check the p-values
# If  > 0.05, we assume normality and can use a parametric test (t-test)
# Otherwise, use a non-parametric test (Wilcoxon rank-sum test)

if (clean_all_shapiro_tt$p.value > 0.05) {
  # Perform t-test
  clean_tt_t_test <- t.test(`TT (ng/mL)` ~ Sex, data = clean_targeted)
  clean_tt_test_type <- "t-test"
  clean_tt_test_statistic <- clean_tt_t_test$statistic
  clean_tt_p_value <- clean_tt_t_test$p.value
  print(clean_tt_t_test)
} else {
  # Perform Wilcoxon rank-sum test
  clean_tt_wilcox_test <- wilcox.test(`TT (ng/mL)` ~ Sex, data = clean_targeted)
  clean_tt_test_type <- "Wilcoxon rank-sum test"
  clean_tt_test_statistic <- clean_tt_wilcox_test$statistic
  clean_tt_p_value <- clean_tt_wilcox_test$p.value
  print(clean_tt_wilcox_test)
}

# Visualize results with boxplot
ggboxplot(clean_targeted, x = "Sex", y = "`TT (ng/mL)`",
          color = "Sex", width = 0.5, 
          ylab = "TT (ng/mL)", xlab = "Sex",
          add = "jitter") + 
  labs(title = paste(clean_tt_test_type, ": statistic =", round(clean_tt_test_statistic, 2), ": pvalue =", formatC(clean_tt_p_value, format = "e", digits = 2)))

# Visualize results with boxplot
ggboxplot(clean_targeted, x = "Sex", y = "`TT (ng/mL)`",
          color = "Sex", width = 0.5, 
          ylab = "Log 10 TT (ng/mL)", xlab = "Sex",
          add = "jitter") + 
  scale_y_log10() +
  labs(title = paste(clean_tt_test_type, ": statistic =", round(clean_tt_test_statistic, 2), ": pvalue =", formatC(clean_tt_p_value, format = "e", digits = 2)))

ggsave("log_clean_tt_statistics_sex.svg", path = svg_path)

```

# Estrogen
```{r E2_SexComparison, echo=TRUE}
# Check the p-values
# If  > 0.05, we assume normality and can use a parametric test (t-test)
# Otherwise, use a non-parametric test (Wilcoxon rank-sum test)

if (all_shapiro_e2$p.value > 0.05) {
  # Perform t-test
  e2_t_test <- t.test(`17B-E2 (ng/mL)` ~ Sex, data = targeted)
  e2_test_type <- "t-test"
  e2_test_statistic <- e2_t_test$statistic
  e2_p_value <- e2_t_test$p.value
  print(e2_t_test)
} else {
  # Perform Wilcoxon rank-sum test
  e2_wilcox_test <- wilcox.test(`17B-E2 (ng/mL)` ~ Sex, data = targeted)
  e2_test_type <- "Wilcoxon rank-sum test"
  e2_test_statistic <- e2_wilcox_test$statistic
  e2_p_value <- e2_wilcox_test$p.value
  print(e2_wilcox_test)
}

# Visualize results with boxplot
ggboxplot(targeted, x = "Sex", y = "`17B-E2 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "17B-E2 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  labs(title = paste(e2_test_type, ": statistic =", round(e2_test_statistic, 2), ": pvalue =", formatC(e2_p_value, format = "e", digits = 2)))
ggsave("e2_statistics_sex.svg", path = svg_path)

ggboxplot(targeted, x = "Sex", y = "`17B-E2 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "Log 10 17B-E2 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  scale_y_log10() +
  labs(title = paste(e2_test_type, ": statistic =", round(e2_test_statistic, 2), ": pvalue =", formatC(e2_p_value, format = "e", digits = 2)))
ggsave("log_e2_statistics_sex.svg", path = svg_path)

# Check the p-values
# If  > 0.05, we assume normality and can use a parametric test (t-test)
# Otherwise, use a non-parametric test (Wilcoxon rank-sum test)

if (clean_all_shapiro_e2$p.value > 0.05) {
  # Perform t-test
  clean_e2_t_test <- t.test(`17B-E2 (ng/mL)` ~ Sex, data = clean_targeted)
  clean_e2_test_type <- "t-test"
  clean_e2_test_statistic <- clean_e2_t_test$statistic
  clean_e2_p_value <- clean_e2_t_test$p.value
  print(clean_e2_t_test)
} else {
  # Perform Wilcoxon rank-sum test
  clean_e2_wilcox_test <- wilcox.test(`17B-E2 (ng/mL)` ~ Sex, data = clean_targeted)
  clean_e2_test_type <- "Wilcoxon rank-sum test"
  clean_e2_test_statistic <- clean_e2_wilcox_test$statistic
  clean_e2_p_value <- clean_e2_wilcox_test$p.value
  print(clean_e2_wilcox_test)
}

# Visualize results with boxplot
ggboxplot(clean_targeted, x = "Sex", y = "`17B-E2 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "17B-E2 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  labs(title = paste(clean_e2_test_type, ": statistic =", round(clean_e2_test_statistic, 2), ": pvalue =", formatC(clean_e2_p_value, format = "e", digits = 2)))
ggsave("clean_e2_statistics_sex.svg", path = svg_path)


ggboxplot(clean_targeted, x = "Sex", y = "`17B-E2 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "Log 10 17B-E2 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  scale_y_log10() +
  labs(title = paste(clean_e2_test_type, ": statistic =", round(clean_e2_test_statistic, 2), ": pvalue =", formatC(clean_e2_p_value, format = "e", digits = 2)))
ggsave("log_clean_e2_statistics_sex.svg", path = svg_path)
```

Progesterone

```{r Progesterone, echo=TRUE}
# Check the p-values
# If  > 0.05, we assume normality and can use a parametric test (t-test)
# Otherwise, use a non-parametric test (Wilcoxon rank-sum test)

if (all_shapiro_p4$p.value > 0.05) {
  # Perform t-test
  p4_t_test <- t.test(`P4 (ng/mL)` ~ Sex, data = targeted)
  p4_test_type <- "t-test"
  p4_test_statistic <- p4_t_test$statistic
  p4_p_value <- p4_t_test$p.value
  print(p4_t_test)
} else {
  # Perform Wilcoxon rank-sum test
  p4_wilcox_test <- wilcox.test(`P4 (ng/mL)` ~ Sex, data = targeted)
  p4_test_type <- "Wilcoxon rank-sum test"
  p4_test_statistic <- p4_wilcox_test$statistic
  p4_p_value <- p4_wilcox_test$p.value
  print(p4_wilcox_test)
}

# Visualize results with boxplot
ggboxplot(targeted, x = "Sex", y = "`P4 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "P4 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  labs(title = paste(p4_test_type, ": statistic =", round(p4_test_statistic, 2), ": pvalue =", formatC(p4_p_value, format = "e", digits = 2)))
ggsave("p4_statistics_sex.svg", path = svg_path)

ggboxplot(targeted, x = "Sex", y = "`P4 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "Log 10 P4 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  scale_y_log10() +
  labs(title = paste(p4_test_type, ": statistic =", round(p4_test_statistic, 2), ": pvalue =", formatC(p4_p_value, format = "e", digits = 2)))
ggsave("log_p4_statistics_sex.svg", path = svg_path)

# Check the p-values
# If  > 0.05, we assume normality and can use a parametric test (t-test)
# Otherwise, use a non-parametric test (Wilcoxon rank-sum test)

if (clean_all_shapiro_p4$p.value > 0.05) {
  # Perform t-test
  clean_p4_t_test <- t.test(`P4 (ng/mL)` ~ Sex, data = clean_targeted)
  clean_p4_test_type <- "t-test"
  clean_p4_test_statistic <- clean_p4_t_test$statistic
  clean_p4_p_value <- clean_p4_t_test$p.value
  print(clean_p4_t_test)
} else {
  # Perform Wilcoxon rank-sum test
  clean_p4_wilcox_test <- wilcox.test(`P4 (ng/mL)` ~ Sex, data = clean_targeted)
  clean_p4_test_type <- "Wilcoxon rank-sum test"
  clean_p4_test_statistic <- clean_p4_wilcox_test$statistic
  clean_p4_p_value <- clean_p4_wilcox_test$p.value
  print(clean_p4_wilcox_test)
}

# Visualize results with boxplot
ggboxplot(clean_targeted, x = "Sex", y = "`P4 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "P4 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  labs(title = paste(clean_p4_test_type, ": statistic =", round(clean_p4_test_statistic, 2), ": pvalue =", formatC(clean_p4_p_value, format = "e", digits = 2)))
ggsave("clean_p4_statistics_sex.svg", path = svg_path)

ggboxplot(clean_targeted, x = "Sex", y = "`P4 (ng/mL)`",
          color = "Sex", width = 0.5,
          ylab = "Log 10 P4 (ng/mL)", xlab = "Sex",
          add = "jitter") +
  scale_y_log10() +
  labs(title = paste(clean_p4_test_type, ": statistic =", round(clean_p4_test_statistic, 2), ": pvalue =", formatC(clean_p4_p_value, format = "e", digits = 2)))
ggsave("log_clean_p4_statistics_sex.svg", path = svg_path)

```
