---
title: "Untargeted_Analysis"
author: "Sneha Michaela Chaturvedi"
date: "05-06-2025"
output: html_document
---

##Set Up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) {
  install.packages("pacman")
  library(pacman)
} 
p_load(tidyverse,readxl,dplyr,stats,ggplot2)
```


```{r LoadDataset, echo=TRUE}
full_dataset = read_excel('./Datasets/32_untargeted_developing_2025.xlsx',sheet="Area",range=NULL)
```
#Format Datafile

```{r CleanUp, echo=TRUE}
#function to convert to numeric
convert_to_numeric <- function(x) {
  x <- as.character(x)
  x[x == "N/A"] <- NA
  as.numeric(x)
}

# Clean the data:
# 1. Remove asterisks from names (*indicates isomers detected)
# 2. Convert numeric columns
# 3. Remove rows where all sample values are NA - relevant if annotated with other experimental samples
full_dataset <- full_dataset %>%
  # First clean names with asterisks
  mutate(Name = gsub("\\*$", "", Name)) %>%
  # Then convert numeric columns and filter NA rows
  mutate(across(4:ncol(.), convert_to_numeric)) %>%
  filter(if_any(4:ncol(.), ~!is.na(.)))

#create complete numeric data set for functions
full_dataset <- cbind(full_dataset[1:3], full_dataset[,(4:27)] %>% replace(is.na(.), NaN))

# Modify sample names for columns 4 to 27
new_col_names <- names(full_dataset)[4:27] %>%
  sub("Area\\. ", "Sample", .)

# Assign the new column names back to the data frame
names(full_dataset)[4:27] <- new_col_names
```

##QC

#Data Visualization
```{r Distribution_Plots}
#metabolite scatter plot
# Reshape the data to long format for plotting
data_long <- full_dataset %>%
  pivot_longer(cols = 4:27, names_to = "Sample", values_to = "Metabolite")

#Remove non-finite values
data_long <- data_long %>%
  filter(is.finite(Metabolite))

# Log-transform the metabolite values
data_long <- data_long %>%
  mutate(ZScore = log10(Metabolite))

# Plot the histogram
ggplot(data_long, aes(x = ZScore)) +
  geom_histogram(binwidth = 0.5, fill = "steelblue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Metabolites",
       x = "Metabolite Z Score",
       y = "Frequency")

# Plot the scatter plot
ggplot(data_long, aes(x = as.factor(Sample), y = Metabolite)) +
  geom_point(size = 1, color = "darkorange") +
  theme_minimal() +
  labs(title = "Metabolite Values per Sample",
       x = "Sample",
       y = "Metabolite Value") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


# Calculate number of metabolites per sample
  metabolite_count_full <- colSums(!is.na(full_dataset[, 4:27]))
  metabolite_count_full <- data.frame(Sample = names(metabolite_count_full), Count = metabolite_count_full)

#Graph
ggplot(data = metabolite_count_full, aes(x = Sample, y = Count)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Number of Metabolites per Sample",
       x = "Sample", y = "Metabolite Count")
```
```{r MetaboliteMissingness, echo=TRUE}
# Function to calculate missingness per metabolite
calculate_missingness <- function(data) {
  # Calculate proportion of NA values for each metabolite
  missing_prop <- rowMeans(is.na(data[,-1]))
  
  # Add missingness to metabolite names
  missing_df <- data.frame(
    metabolite = data[,1],
    missing_proportion = missing_prop
  )
  
  return(missing_df)
}

#Run function
 missing_stats_full <- calculate_missingness(full_dataset)

#Plot
ggplot(missing_stats_full, aes(x = missing_proportion)) +
  geom_histogram(bins = 20, fill = "steelblue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Missing Values",
       x = "Proportion Missing",
       y = "Count") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  geom_text(stat='count', aes(label=..count..), vjust=-1.5, color="black", size=3.5, position = position_stack(vjust = 0.5))
  


```

#Outlier Detection/Removal
```{r OutlierSamples, echo=TRUE}
identify_outlier_samples <- function(data, threshold = 3, i = c(4:27)) {
  # Calculate total intensity per sample
  sample_sums <- colSums(data[,i], na.rm = TRUE)
  
  # Calculate z-scores for sample intensities
  z_scores <- scale(sample_sums)
  
  # Identify outliers (samples with z-scores above threshold)
  outliers <- which(abs(z_scores) > threshold)
  
  return(list(
    outlier_indices = outliers,
    sample_sums = sample_sums,
    z_scores = z_scores
  ))
}

# Run function and save output
outliers_info <- identify_outlier_samples(full_dataset)

# Convert outlier indices to actual column names
outlier_columns <- colnames(full_dataset)[outliers_info$outlier_indices + 3] # Adjusted for the correct indexing
print(outlier_columns)

# Remove the outliers from the data set
clean_dataset <- full_dataset %>% select(-all_of(outlier_columns))
```

#Data Re-visualization after Outlier Exclusion

```{r ReDistribution_Plots}
# Calculate number of metabolites per sample
  metabolite_count_clean <- colSums(!is.na(clean_dataset[, 4:27]))
  metabolite_count_clean <- data.frame(Sample = names(metabolite_count_clean), Count = metabolite_count_clean)

#Graph
ggplot(data = metabolite_count_clean, aes(x = Sample, y = Count)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Number of Metabolites per Sample",
       x = "Sample", y = "Metabolite Count")

#Calculate total intensity per sample
  total_intensity_clean <- colSums(clean_dataset[, 4:27], na.rm = TRUE)
  total_intensity_clean <- data.frame(Sample = names(total_intensity_clean), Intensity = total_intensity_clean)
  
#Plot
ggplot(data = total_intensity_clean, aes(x = Sample, y = Intensity)) +
  geom_bar(stat = "identity", fill = "darkorange") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Intensity of Total Metabolites per Sample",
       x = "Sample", y = "Total Intensity")

#Missing Stats
 missing_stats_clean <- calculate_missingness(clean_dataset)

#Plot
ggplot(missing_stats_clean, aes(x = missing_proportion)) +
  geom_histogram(bins = 20, fill = "steelblue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Missing Values",
       x = "Proportion Missing",
       y = "Count") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  geom_text(stat='count', aes(label=..count..), vjust=-1.5, color="black", size=3.5, position = position_stack(vjust = 0.5))
  
```
  


Split annotated and unannotated
```{r Dataframe_Split}
# Assuming your dataframe is named 'df'
annotated <- full_dataset_num[!is.na(full_dataset_num$Name) & full_dataset_num$Name != "", ]
unannotated <- full_dataset_num[is.na(full_dataset_num$Name) | full_dataset_num$Name == "", ]
```


#Annotated Metabolomics Analysis
Identify Duplicates

```{r LoadAnnotation, echo=TRUE}
Annotation = read_excel('./Datasets/32_untargeted_developing_2025.xlsx',sheet="Annotation",range=NULL)

Annotation <- Annotation %>%
  # First clean names with asterisks
  mutate(Name = gsub("\\*$", "", Name))

# split file
A_annotated <- Annotation[!is.na(Annotation$InChiKey) & Annotation$InChiKey != "", ]
A_unannotated <- Annotation[is.na(Annotation$InChiKey) | Annotation$InChiKey == "", ]
```

```{r Duplicate_Identification}

# Find duplicate names in the column "InChiKey"
duplicates <- A_annotated %>%
  group_by(InChiKey) %>%
  filter(n() > 1) %>%
  arrange(Name)

# Create a histogram plot
library(ggplot2)

# Calculate the count of occurrences for each duplicate name
duplicate_counts <- duplicates %>%
  group_by(InChiKey) %>%
  summarise(count = n())

# Create a histogram
ggplot(duplicate_counts, aes(x = count)) +
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") +
  ggtitle("Histogram of Duplicate InChiKey") +
  xlab("Count of Duplicates") +
  ylab("Frequency")

# Print table of all duplicate names
print(duplicates)

# Optionally, you could view the duplicate counts separately
print(duplicate_counts)
```
Create non-duplicate dataframe

```{r DuplicateRemoval, echo=TRUE}

# Assuming your dataframe of duplicates is named 'duplicates'
# Calculate % Relative Standard Deviation (% RSD) for each row
annotated <- annotated %>%
  rowwise() %>%
  mutate(
    mean_value = mean(c_across(4:27), na.rm = TRUE),
    std_dev = sd(c_across(4:27), na.rm = TRUE),
    percent_RSD = (std_dev / mean_value) * 100
  ) %>%
  ungroup()

annotated <- annotated %>%
  left_join(A_annotated %>% select(Compound.ID, InChiKey), by = "Compound.ID")

# Create a new dataframe that keeps only non-NA RSD values, and then finds the duplicate with the lower % RSD for each InChiKey
clean_annotated <- annotated %>%
  filter(!is.na(percent_RSD)) %>%
  group_by(InChiKey) %>%
  filter(percent_RSD == min(percent_RSD, na.rm = TRUE)) %>%
  ungroup()
```

Imputation

```{r MinImpute}

# Assuming your dataframe is named 'clean_annotated'
# Imputation function to replace NaN with 1/5th of the minimum value in each row
min_value_imputation_row <- function(df, cols) {
  df <- df %>%
    rowwise() %>%
    mutate(
      across(all_of(cols), ~ replace_na(., min(c_across(all_of(cols)), na.rm = TRUE) / 5))
    ) %>%
    ungroup()
  return(df)
}

# Apply imputation to columns 4 to 27 in the clean_annotated dataframe
clean_annotated_imputed <- min_value_imputation_row(clean_annotated, 4:27)

```


Normalization

```{r Normalization}

# Z-score normalize metabolites across samples
normalized_clean_annotated <- clean_annotated_imputed
normalized_clean_annotated[4:27] <- as.data.frame(scale(clean_annotated_imputed[4:27], center = TRUE, scale = TRUE))

```

Clean Sample names

```{r CleanSampleNames, echo=TRUE}
# Assuming your dataframe is named 'normalized_clean_annotated'
# Modify column names for columns 4 to 27
new_col_names <- names(normalized_clean_annotated)[4:27] %>%
  sub("Area\\. ", "Sample", .)

# Assign the new column names back to the dataframe
names(normalized_clean_annotated)[4:27] <- new_col_names

```

Assign Metadata
```{r Metadata, echo=TRUE}
metadata = read_excel('./Datasets/metadata.xlsx',sheet="metadata",range=NULL)

# Ensure the "SampleName" column in metadata matches these sample names
metadata$Sample <- paste0("Sample", metadata$SampleName)

# In case the metadata 'Sample' column needs to be redefined to match main_df column names
metadata <- metadata %>%
  select(Sample, Sex, GW)

# Merge metadata with the long-format main dataframe
merged_df <- normalized_clean_annotated %>%
left_join(metadata, by = "Sample")

# Pivot the long-format dataframe back to the wide format if necessary
final_untargeted_dataset <- merged_df %>%
 pivot_wider(names_from = Sample, values_from = Value)

```
